### ISSUE TITLE
required property in referenced response

### ISSUE THREAD

**Issue by gbkwiatt** [RuntimeTools/OpenAPIValidators#102]
In this scenario my required properties are checked in the main response, not in nested config object. So it fails validation
yaml:
```yaml
/system/config:
 get ... 

responses:
        '200':
          description: Config list
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Config'
                  - $ref: '#/components/schemas/dataToken'

components:
  schemas:
   Config:
     type: object
      properties:
        systemName:
          type: string
     required:
        - systemName
```

if I change `systemName` to `config`  on required, it passes validation. which menas doesnt matter where required is, it always checks from main response object ?

**Comment by rwalle61** [comment]
Hi @gbkwiatt, thanks for raising this. 

What’s in your `dataToken` schema, and what’s the validation error you’re getting?

**Comment by gbkwiatt** [comment]
dataToken schema is  just  another properties which are fine in this case. 
without it I get same errors 
```yaml
dataToken:
      type: object
      properties:
        errorMessage:
          type: string
          example: ''
        errorCode:
          type: string
          example: ''
          enum:
            - ''
        token:
          type: string
          example: hbGciOiJIUzI1NiIsInR5cCI6...
```

validation error just says response should have required `systemName`, which it does but in `response.body.config.systemName`, but it looks for `systemName` inside `response.body` instead.

**Comment by rwalle61** [comment]
Okay, it looks like this isn't a bug, and your response schema is slightly different to your response body. 

Your response body has `response.body.config.systemName`, but your response schema currently does not actually mention a `config` property. (Calling your schema `Config` does not make a difference in this respect).

Try this response schema:
``` 
        content:
            application/json:
              schema:
                allOf:
                  - type: object
                     properties:
                       config:
                         $ref: '#/components/schemas/Config'
                  - $ref: '#/components/schemas/dataToken'
```

Does that resolve your error?

(And if you get another error to do with `allOf`, check you are using `allOf` correctly - see this explanation https://github.com/RuntimeTools/OpenAPIValidators/issues/46#issuecomment-634572398)

**Comment by gbkwiatt** [comment]
Not sure what do you mean doesn't mention config?
I'm the code above under properties there is config property which schema is referenced, also if I add there required: - config, it is saysfied.
But then I can check required properties in the config itself. 
I did read a bit about allOf problem, seems like it's widely misunderstood. But I can't see any workaround or correct way to do such a thing.
