### ISSUE TITLE
Use not only global expect

### ISSUE THREAD

**Issue by mhozhynewscorp** [RuntimeTools/OpenAPIValidators#121]
**OpenAPI version**
N/A

**Is your feature request related to a problem? Please describe.**

I'm not sure about the `chai`, but as for the `jest`, I faced an obvious limitation.

This plugin can only work in a test environment. To use it in a usual environment, for example in a production that returns an object or an issue occurring with it as an error, you have to do this:
```js
const expect = require('expect');
const schema = path.resolve('./path/to/schema');
global.expect = expect;
jestOpenAPI(schema);
```

It works but you should keep in mind that using global variables is an undesirable practice in javascript.

**Describe the solution you'd like**
Add a setter to the function and store the instance inside the function's module.

```js
let localExpect = null;

function jestOpenAPI(pathOrObject) {
  const expect = localExpect || global.expect;
  // plugin magic
}

jestOpenAPI.setExpect = function (instance) {
  localExpect = instance;
};

module.exports = jestOpenAPI;

```

**Describe alternatives you've considered**
Just extend function signature and pass instance directly

**Additional context**
There's no such thing.

**Are you going to resolve the issue?**
Yes

**Comment by rwalle61** [comment]
Thanks for raising this @mhozhynewscorp! 

I am open to your feedback about how Jest users prefer to modify `expect`, especially as I personally use this package more in `chai` than `jest` myself.

Currently we modify `expect` following `jest-extended`'s implementation: https://github.com/jest-community/jest-extended#jest-v23 and https://github.com/jest-community/jest-extended/blob/master/src/index.js#L3

I haven't looked in depth as to the pros and cons of doing it this way, so happy for Jest users to explain

**Comment by mhozhynewscorp** [comment]
Hi @rwalle61! Thank you for the clarifications, quick response and sample with `jest-extended`.  In that case, we can say that it is an established ecosystem solution.

Personally, if we approach this issue practically, I do not see any issues when using the global `expect`. It's a million-dollar chance that this will lead to some real problems. 

So it's up to you whether or not to close issue.

**Comment by rwalle61** [comment]
I think we should let people use this plugin like `jest-extended`, i.e. simply doing:
```
const schema = path.resolve('./path/to/schema');
jestOpenAPI(schema);
```

That modifies `global.expect`. Perhaps some users want to use this package without modifying `global.expect`, e.g. doing:
```
const expect = jestOpenAPI(schema).expect;
```


If users want this feature, I would be happy to take a PR implementing it in addition to the existing  way of using this plugin (calling `jestOpenAPI(schema)`).

What do you think? One option is to close this for now, and if anyone else wants the feature they can reopen this?

**Comment by rwalle61** [comment]
I assume we should close this for now. If anyone wants this feature, feel free to reopen this :)
