### ISSUE TITLE
OpenApi 2.0: basePath is ignored

### ISSUE THREAD

**Issue by tgiardina** [RuntimeTools/OpenAPIValidators#159]
**Which package are you using**?
`chai-openapi-response-validator`

**OpenAPI version**
2

**Describe the bug**
In my `swagger.json`, `"basePath": "/api"` is ignored, so I get the following error:

```
AssertionError: expected res to satisfy API spec

expected res to satisfy a '201' response defined for endpoint 'POST /api/users' in your API spec
res had request path '/api/users', but your API spec has no matching path
 
Paths found in API spec: /users
```

**Possible Solution**
My use case works if I edit the `pathsObject` function in `packages/chai-openapi-response-validator/lib/openapi-validator/lib/classes/AbstractOpenApiSpec` to be:
```
  pathsObject() {
    let { paths }= this.spec;
    if(this.spec.basePath) {
      const prependedPaths = {};
      Object.keys(paths).forEach( pathName => {
        prependedPaths[`${this.spec.basePath}${pathName}`] = paths[pathName];
      });
      paths = prependedPaths;
    }
    return paths;
  }
```

I can then switch `commonTestResources/exampleOpenApiFiles/valid/openapi2.json` to use a basePath, and `npm test` will still pass. However, `npm test:ci` blows up, which I don't understand.

**Comment by rwalle61** [comment]
Thanks for this @tgiardina! I'm at work right now so will take a proper look as soon as I can.

Your solution (editing `pathsObject` in `AbstractOpenApiSpec`) may well work. What's the errors when you run `npm run test:ci`?

From a longer term code maintenance perspective, it would be better to make your changes in `OpenAPI2Spec.js` because this fix is specific to OpenAPI 2. 

FYI, for OpenAPI 3 specs we [already have a related mechanism for `servers` applying to all the paths](https://github.com/RuntimeTools/OpenAPIValidators/blob/master/packages/chai-openapi-response-validator/lib/openapi-validator/lib/classes/OpenApi3Spec.js#L65). Maybe we need to generalise that for OpenAPI 2 as well, but that will require more thought.

I'll give this another look when I can. Very happy for you to investigate further if you're interested :)

**Comment by rwalle61** [comment]
Also, the fastest way to resolve this would be if you could recreate the bug on a branch using [this template](`https://github.com/RuntimeTools/OpenAPIValidators/blob/master/packages/chai-openapi-response-validator/test/bugRecreationTemplate.test.js`), then everyone's crystal clear on the problem.

And if you include your temporary solution on that branch, I can recreate any errors you have running `npm test:ci`

**Comment by tgiardina** [comment]
Thanks for the quick response, @rwalle61! I may have time later this week to take another look at it. 

Re the template, I was a bit confused how to use it properly. Am I supposed to make a PR with an both edited template and an edited yaml file?

**Comment by rwalle61** [comment]
>Am I supposed to make a PR with an both edited template and an edited yaml file?

Yep, just make those edits on your branch (don't have to PR), and put the link here. 

The more minimal the reproduction example the better. 

(I'll add these instructions to the readme / the template)

**Comment by tgiardina** [comment]
Okay, thanks for the explanation! Here's [the link to my fork](https://github.com/tgiardina/OpenAPIValidators). There's only one commit and two files (barely) changed, so it should be easy to parse.

> From a longer term code maintenance perspective, it would be better to make your changes in `OpenAPI2Spec.js` because this fix is specific to OpenAPI 2.
I 100% agree with you on this. I will keep it in mind if I get a chance to make a PR (I may have some time tomorrow).

Thanks again for being so responsive!

**Comment by rwalle61** [comment]
Thanks for that minimal recreation, and a PR would be welcome!

As mentioned I would probably fix this in `OpenAPI2Spec.js`.

If you want my suggested implementation:

We already handle OpenAPI 3 servers in `OpenAPI3Spec.js` in the [`findOpenApiPathMatchingPathname` function](https://github.com/RuntimeTools/OpenAPIValidators/blob/master/packages/chai-openapi-response-validator/lib/openapi-validator/lib/classes/OpenApi3Spec.js#L66).

`OpenAPI2Spec.js` has an equivalent [`findOpenApiPathMatchingPathname` function](https://github.com/RuntimeTools/OpenAPIValidators/blob/master/packages/chai-openapi-response-validator/lib/openapi-validator/lib/classes/OpenApi2Spec.js#L6)), so the fix should probably be in there.

Note that [OpenAPI 3 specs can have multiple `servers`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#oasServers). This is why our code for OpenAPI 3 specs [iterates through all combinations of server and path until it finds the server + path combo that the user is using](https://github.com/RuntimeTools/OpenAPIValidators/blob/master/packages/chai-openapi-response-validator/lib/openapi-validator/lib/classes/OpenApi3Spec.js#L66). 

By contrast, an OpenAPI 2 spec [can have only 1 `basePath`, and if `basePath` isn't provided, it defaults to `/`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields). (See also [this](https://swagger.io/docs/specification/2-0/api-host-and-base-path)).

So I think the fix in `OpenAPI2Spec.js` just needs to: 
1. determine what the basePath is (`/` or something else)
2. remove that from the request pathname
3. then do the matching as normal

so given the current function in `OpenAPI2Spec.js` is:
```js
findOpenApiPathMatchingPathname(pathname) {
    const openApiPath = utils.findOpenApiPathMatchingPossiblePathnames(
      [pathname],
      this.paths(),
    );
    if (!openApiPath) {
      throw new ValidationError('PATH_NOT_FOUND');
    }
    return openApiPath;
  }
```

We probably want something like:

```js
findOpenApiPathMatchingPathname(pathname) {
    const basePath = this.spec.basePath || '/' // or set `this.spec.basePath` in the constructor, like https://github.com/RuntimeTools/OpenAPIValidators/blob/master/packages/chai-openapi-response-validator/lib/openapi-validator/lib/classes/OpenApi3Spec.js#L20 
    const pathnameWithoutBasePath = getPathnameWithoutBasePath(basePath, pathname),
    const openApiPath = utils.findOpenApiPathMatchingPossiblePathnames(
      [pathnameWithoutBasePath],
      this.paths(),
    );
    if (!openApiPath) {
      throw new ValidationError('PATH_NOT_FOUND');
    }
    return openApiPath;
  }
```

There may be a different / better solution, and I haven't tested that, so very happy to hear your thoughts and/or a different implementation!

**Comment by tgiardina** [comment]
Funny timing! I just created a PR doing essentially what you outlined! I'll let you check it out rather than repeating myself here.

**Comment by rwalle61** [comment]
TODO for me
- [] port to Jest
- [] release

**Comment by rwalle61** [comment]
Published 🎉 

Thanks @tgiardina for your code and discussion, a pleasure having your contribution.

Fyi I managed to [remove some of those `if` conditions for the error message](https://github.com/RuntimeTools/OpenAPIValidators/pull/185/files#diff-585a46b55b8d80d190a56a2a5ff41a8bR40) by spotting that we had a few tests covering invalid `req.path`s.

I'll simplify the codebase further and convert it to TypeScript when I can, to make it easier for future contributors.

If you have any feedback on your contribution experience, let me know 😄

**Comment by rwalle61** [comment]
Please confirm v0.10.0 actually fixes your use case, and if so close this!

**Comment by tgiardina** [comment]
Just checked. Everything looks like it's working!
