### ISSUE TITLE
oneOf not working as intended

### ISSUE THREAD

**Issue by Yilong94** [RuntimeTools/OpenAPIValidators#177]
**Which package are you using**?
`jest-openapi`

**OpenAPI version**
3

**Describe the bug**
`oneOf` does not work as intended. Even though the response object matches one of the schemas, it throws an error

**To Reproduce**

Using this trivial example below
```
  /application/test:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  data:
                    oneOf:
                      - type: object
                        properties:
                          hello:
                            type: string
                          world:
                            type: boolean
                          bye:
                            type: string
                          earth:
                            type: boolean
                      - type: object
                        properties:
                          hello:
                            type: string
                          world:
                            type: boolean
```
I generated an object with the following structure
```
{
  code: "OK",
  data: {
              hello: "123",
              world: true,
              bye: "123",
              earth: false
           }
}
```

I received the following error which states that `data should match exactly one schema in oneOf`
![Screenshot 2020-10-05 at 8 32 25 PM](https://user-images.githubusercontent.com/17191867/95079936-e6bbb380-0749-11eb-92fd-f7293d8a83fa.png)

**Expected behavior**
No error should be thrown

**Comment by rwalle61** [comment]
Thanks for raising this :)

I think this is expected OpenAPI behaviour. Your res body is matching 2 schemas, rather than just oneOf them. 

(oneOf is not oneOrMoreOf)

I will double check when I have time. Fyi this issue reminds me of an old issue where we were similarly confused about `allOf`, which I will link here when I'm on my laptop

**Comment by Yilong94** [comment]
omg yes you are right. It didnt dawn upon me that it was matching both schema until you mentioned it. I forgot that schemas can match objects with additional properties. Thank you good sir for pointing it out!

I know this probably isnt the place to ask but thought you might have an answer off the top of your head. In that case, should I be using 'anyOf' to describe this API, or is there a better way to work around it? It seems rather odd to be using 'anyOf' when I actually mean 'oneOf'.

Also thank you for your hard work on this library! Mad props to you!

**Comment by rwalle61** [comment]
You said it yourself, "schemas can match objects with additional properties", unless you specify `additionalProperties: false` on your schema :)

I can't find a nice summary of `additionalProperties`, but here's a starting point https://swagger.io/docs/specification/data-models/keywords/?sbsearch=additionalproperties

**Comment by Yilong94** [comment]
yes this works! thank you very much 👍
