### ISSUE TITLE
Property 'toSatisfyApiSpec' does not exist on type 'Matchers<void, Response>'

### ISSUE THREAD

**Issue by ghost** [RuntimeTools/OpenAPIValidators#285]
**Are you using jest or chai?**
jest

**Are you using OpenAPI 2, 3.0.X, or 3.1.0?**
3.0

**Describe the bug clearly**
Following the example for using `jest-openapi` when running the tests I get this message: 
```
tests/openapi.test.ts:148:34 - error TS2339: Property 'toSatisfyApiSpec' does not exist on type 'Matchers<void, Response>'.
```

The environment is node 16.x running inside a docker container, configured as Typescript 4.8.x, ESM, and jest 27.x

**Steps to reproduce the bug:**
* Install the library with `yarn add -D jest-openapi`
* create a test following the example given here [https://github.com/openapi-library/OpenAPIValidators/tree/master/packages/jest-openapi#readme](url)
* run the test

**What did you expect to happen instead?**
Test should run successfully

**Comment by markdowney** [comment]
Got it to work by installing types from `@types/jest` and removing  
```
import { expect } from '@jest/globals';
```
