### ISSUE TITLE
Support for OAS3 Example Object

### ISSUE THREAD

**Issue by blelump** [RuntimeTools/OpenAPIValidators#55]
**OpenAPI version**
3

**Is your feature request related to a problem? Please describe.**
No, it is an overall improvement leading to almost no code for testing happy path scenarios.

**Describe the solution you'd like**
Since OAS3 supports example objects\[1\], are there any objections or difficulties against using them and simply running all the specs from OAS with the payload from OAS? Thanks to it, a bare minimum (a happy path) can be achieved more or less without any coding.

**Describe alternatives you've considered**
None.

**Additional context**

\[1\]: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#exampleObject

**Comment by rwalle61** [comment]
Thanks for raising this.

So if I understand you correctly, you’d like to able to write (e.g.) `expect(app).to.satisfyExamplesInApiSpec` to test that your server satisfies all response specs defined in your OpenAPI spec?

Are you trying to test your server, and/or test that you’ve correctly defined your examples in the OpenAPI spec?

My initial thoughts are that this functionality could be nice. 

It is a bit different to what this package currently offers (test each response  individually). I’m open to new features, as long as they make sense to belong to this package and not another one. For example, how is this different to what Dredd offer? (They let you test your entire app with one command)

Also, what we would do when there are failures - would lots of failures be confusing for the user?

These are just my initial thoughts, I welcome further discussion, and I’ll think about it more too

**Comment by blelump** [comment]
Hi @rwalle61 , thanks for answering!

So my thoughts regarding this were to be able to cover OAS defined endpoints for the happy path use cases. OAS helps you with definition of some sample data, which can be used for simple tests. So such test, ie. for `POST /tickets` with sample data should return with 20x code thanks to this sample data defined in example object.

Besides Dredd, there is also https://github.com/kiwicom/schemathesis which does similar thing – covers the whole OAS, but to me this is also a limitation. Consider for instance API development, where not all endpoints are ready, whereas OAS is well defined. So you'd like to add new ones as they become ready to test. So I imagine you test the endpoints that are ready to test, ie:
```
[endpoints].forEach((endpoint) => {
  expect(...).to.satisfyExamplesInApiSpec;
});
```
Moreover you can also define example object in the response so I imagine we can also test for the responses.

The above can also be implemented internally, by just parsing OAS spec, getting example object and sending data to the endpoint got from the example object. Finally check the result against example object from OAS and compare with response.

Another thing which for me personally is important is that there is only one place of truth for the tests. So we have, lets call them `unit specs`, which are all the specs discussed above so you cover the happy paths and you're sure that all endpoints are bug-free (and only this). But we also have more sophisticated specs, closer to acceptance ones, where you follow some common real use case and check against more custom expectations that are important to check. Just to put some light on our environment: we use AWS api gateway, which internally integrates (via lambda or simple mapping in VTL) more third parties so a lot of different pieces which reasonable coverage is to have few acceptance specs. All that, I mean "units" and acceptance ones can be easily achieved ie. with this plugin and eventually some extensions, hence we cover what we need.

**Comment by rwalle61** [comment]
Sorry for the delay @blelump, my initial thought months ago was that this is quite a large enhancement and probably out of our scope. I still think it is out of scope for now, and as we've not received any interest from other users I'll probably close this. However, it may come in scope in future (read below).

### Summary 

If I'm summarising correctly, you'd like to easily check that your OpenAPI spec **and server** are correct. Ideally, you'd check this endpoint by endpoint. For example, by doing 
```
expect('http://host/endpoint').to.satisfyExamplesInApiSpec;
```
which:
1. parses your OpenAPI spec, and extracts the example request body for '/endpoint'
2. makes that request to 'http://host/endpoint'
3. validates the response against your spec (like running our existing `expect(response).toSatisfyApiSpec`)

I can certainly see the value of this. However, you can already do steps 2 and 3 easily. So you're missing only step 1: an API to do `getExampleRequestBody(openApiSpec, endpoint)` or `openApiSpec.getExampleRequestBody(endpoint)`.

The current scope of our jest and chai plugins is to assert on a `response` or `object` and validate that it is as defined in your OpenAPI spec. So I think such an API is out of current scope. 

### Future

However, such as API would be useful, for example to you. And our jest and chai plugins do use [an internal OpenAPI spec parsing dependency, 'openapi-validator'](https://github.com/RuntimeTools/OpenAPIValidators/blob/master/packages/chai-openapi-response-validator/lib/openapi-validator/package.json). Currently `openapi-validator` is just internal to us, but I have considered publishing it as an npm package. If we do, then it could well make sense to expose `getExampleRequestBody(openApiSpec, endpoint)`.

What do you think?

**Comment by blelump** [comment]
Hi @rwalle61 !

After a few months later I can say a bit more. My initial thought was to use the example object(s) as a payload for acceptance tests for given API exposed under base URL. However, now I'd debate about the real usefulness of this, especially when the endpoint, for instance, requires additional dependencies. So in the end you are forced to manage it kinda manually to cover the test dependencies. OAS itself would not provide all needed input so – probably – you would end up in a custom tests anyway.

What I'm doing right now is basically what you've described in points 1-3 except the extraction. I think it's wiser to keep everything in one place, especially the test payload so you see what's exactly is being sent by just seeing the test code (without migrating to OAS file). However, on the other hand OAS is a kind of "contract" between the implementer (server) and consumer (clients) so all parties see what goes into the endpoint which also could be useful to keep it there, I mean in OAS.

**Comment by rwalle61** [comment]
It's interesting to hear an update on your use case. Yes I think that although OAS examples  can be useful, on their own they are not sufficient for acceptance tests of your server's behaviour. 

Btw have you heard of / used Pact? I haven't used it myself but it may be a solution for your use case

As for this issue, shall we close it?

**Comment by blelump** [comment]
Haven't heard of Pact, thanks for the tip !
