### ISSUE TITLE
Missing module declaration in jest-openapi types

### ISSUE THREAD

**Issue by BenGu3** [RuntimeTools/OpenAPIValidators#73]
**OpenAPI version**
2 and 3

**Describe the bug**
When importing jest-openapi with Typescript, it gives the following error:
`File '/sandbox/node_modules/jest-openapi/index.d.ts' is not a module`.
This causes a TS error in the import and also does not add `toSatisfyApiSpec` or `toSatisfySchemaInApiSpec` to the jest Matchers type, giving another TS error when using those matchers in tests.

**To Reproduce**
https://codesandbox.io/s/practical-haze-9cnxt?file=/src/index.ts

**Expected behavior**
The `jestOpenAPI` function is the default export in the Typescript declaration file.

**Comment by BenGu3** [comment]
Just for context, it looks like we also get this error if you try to build a Typescript file importing the package (which we ended up avoiding by not building our test directories 👍 ). That PR will also fix this TS error.

`TS2669: Augmentations for the global scope can only be directly nested in external modules or ambient module declarations.`

**Comment by rwalle61** [comment]
Thanks for catching and fixing this bug!

**Comment by rwalle61** [comment]
Will release in the morning https://github.com/RuntimeTools/OpenAPIValidators/pull/75
