### ISSUE TITLE
RequestPromiseResponse json body

### ISSUE THREAD

**Issue by ludeknovy** [RuntimeTools/OpenAPIValidators#80]
**Describe the bug**
RequestPromiseResponse throws `TypeError: res.body.replace is not a function`. This happens when request is made with `json: true`, thus the retuned value is not json string but object.

**To Reproduce**
 * Send request with `json: true`, i.e: `{ method: 'GET', json: true, url: 'your-url',  resolveWithFullResponse: true, simple: false}`
* assert that response with expect(response).toSatisfyApiSpec()

**Expected behavior**
Handle `json` without throwing an error.

The problem is on line 7 in RequestPromiseResponse:
`this.body = res.body.replace(/"/g, '');`

**Comment by rwalle61** [comment]
thanks for this! Should be a straightforward fix. Would you like to submit a PR?

Otherwise I will see when I have time to test and fix this

**Comment by ludeknovy** [comment]
@rwalle61 I might submit a PR.

**Comment by rwalle61** [comment]
thanks!

**Comment by rwalle61** [comment]
Released!
